# Generated by Django 4.1.7 on 2023-03-08 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0002_rename_macid_treemodel_macid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemodel',
            name='nick',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
