# Generated by Django 4.1.7 on 2023-03-08 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0003_alter_treemodel_nick'),
    ]

    operations = [
        migrations.AddField(
            model_name='treemodel',
            name='state',
            field=models.CharField(choices=[('0', 'NORMAL'), ('1', 'DANGER'), ('2', 'FALLEN')], default='0', max_length=1),
        ),
    ]
