# Generated by Django 4.1.7 on 2023-03-08 13:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0004_treemodel_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='treemodel',
            name='last_update',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='treemodel',
            name='state',
            field=models.CharField(choices=[('0', 'NORMAL'), ('1', 'HIGH_TEMPERATURE'), ('2', 'VIBRATION_SENSE'), ('3', 'ACCELERATION_SENSE'), ('4', 'FALLEN')], default='0', max_length=1),
        ),
    ]
