# Generated by Django 4.1.7 on 2023-03-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0005_treemodel_last_update_alter_treemodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemodel',
            name='last_update',
            field=models.DateTimeField(blank=True),
        ),
    ]
