# Generated by Django 4.1.7 on 2023-03-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0006_alter_treemodel_last_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemodel',
            name='last_update',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
