# Generated by Django 4.1.7 on 2023-03-08 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0009_alter_treemodel_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemodel',
            name='nick',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
