# Generated by Django 4.1.7 on 2023-03-08 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trees', '0010_alter_treemodel_nick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='treemodel',
            name='macid',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
